# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import welut.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbookConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='ebooks/%Y/%m/%d', validators=[welut.models.conv_validators], verbose_name='Ebook file')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Ebooks Converter',
                'verbose_name': 'Ebook Converter',
            },
        ),
    ]
