# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ebook_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_file', to='welut.EbookConverter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
